### PR TITLE
Include getting started / initialization example in ReadMe.md

### PR DESCRIPTION
**Pull request by steve-ross**
I added some examples around initializing components due to some confusion around why dropdowns, accordions, etc do not get initialized automatically re: Semantic-Org/Semantic-UI#1618 (comment)
Hopefully this will cut down on the "non-issue" issues that get created for "my dropdown, toggle etc doesn't show properly..."

### CODE REVIEW

**Comment by flemay** [comment]
@steve-ross thanks for the examples! Would it be a good idea to put those changes in the wiki instead?

**Comment by steve-ross** [comment]
Think it's worth mentioning in the wiki and the ReadMe since a lot of people go straight to the source (ReadMe) instead of going the 'preferred' route.

**Comment by flemay** [comment]
@steve-ross I would do one or the other! I would have a link to point to the wiki. The advantage of the wiki is we don't need to publish the package all the time a change is made.

**Comment by steve-ross** [comment]
So wiki then? I was just following the suggestion from a comment on a
closed issue.
On Tue, Oct 13, 2015 at 12:55 AM Frederic Lemay notifications@github.com
wrote:

> @steve-ross https://github.com/steve-ross I would do one or the other!
> I would have a link to point to the wiki. The advantage of the wiki is we
> don't need to publish the package all the time a change is made.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Semantic-Org/Semantic-UI-Meteor/pull/71#issuecomment-147601152
> .
> 
> ## 
> 
> Oak.Works

Steve Ross
[O](912) 268-0444

[M](912) 344-8113
[IM] steve@oak.works

**Comment by nooitaf** [comment]
As there is no wiki and its reasonably short i'll merge this into readme ;)

**Pull request merged**
